### ISSUE TITLE
Зачем?

### ISSUE THREAD

**Issue by parfenovvs** [EugeneBo/BasicRecycleViewList#2]
https://github.com/EugeneBo/BasicRecycleViewList/blob/aa141a69dedeb7940d8254b6da2e9271a8e6522d/app/src/main/java/eugenebo/com/github/basicrecycleviewlist/Contact.java#L50

**Comment by EugeneBo** [comment]
Чтобы при одинаковых именах у объектов был одинаковый hashCode и цвет аватара соответственно (т.к. цвет генерируется в зависимости от hashCode объекта)

**Comment by parfenovvs** [comment]
тут не от целиком имени надо, а например только от первой буквы. Хэшкод переопределяют не для UI штук

**Comment by EugeneBo** [comment]
Понял тебя. Зачем хэш-код переопределяют конечно знаю)))  да - перемудрил пожалуй с генерацией цвета
