### ISSUE TITLE
Просто ItemView

### ISSUE THREAD

**Issue by parfenovvs** [EugeneBo/BasicRecycleViewList#6]
https://github.com/EugeneBo/BasicRecycleViewList/blob/dbe1eae3376bfbca574ce5fb610e08900b48bb9b/app/src/main/java/eugenebo/com/github/basicrecycleviewlist/RecycledItemView.java#L3

**Comment by EugeneBo** [comment]
Не очень хорошо будет. 
Уже существует `interface ItemView`  в android.support.v7.view.menu

**Comment by parfenovvs** [comment]
Ну он же в другом пакете

**Comment by EugeneBo** [comment]
Ну чисто по невнимательности, гипотетически, человек бы мог потом ошибиться, при создание нового типа Item
