### ISSUE TITLE
Это лучше делать прямо во ViewHolder

### ISSUE THREAD

**Issue by parfenovvs** [EugeneBo/BasicRecycleViewList#8]
https://github.com/EugeneBo/BasicRecycleViewList/blob/dbe1eae3376bfbca574ce5fb610e08900b48bb9b/app/src/main/java/eugenebo/com/github/basicrecycleviewlist/MainActivity.java#L106

**Comment by EugeneBo** [comment]
Читал, что круто, когда ViewHolder устроен как можно проще, и не круто, если там присутствует какая-то лишняя логика, которая может тормозить скролящийся список. 
Это не верное суждение?

**Comment by parfenovvs** [comment]
Верное. Но в этом случае еще хуже, когда активити знает о таких вещах
